server:
  port: 8080

spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:
        - id: h2-console
          uri: lb://article-server
          predicates:
            - Path=/h2-console
          filters:
            - RewritePath=/(?<segment>.*), /api/article/$\{segment}

        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/api/user/sign-up, /api/user/login, /api/user/check/**

        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/api/user/**
          filters:
            - JwtVerifyFilter


        - id: article-server
          uri: lb://article-server
          predicates:
            - Path=/api/article/save, /api/article/delete, /api/article/update
          filters:
            - JwtVerifyFilter

        - id: article-server
          uri: lb://article-server
          predicates:
            - Path=/api/article/**


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

token:
  header: X-TOKEN
  prefix: "Bearer "
  secret: VGhpc2lzSnd0U2VjcmV0S2V5Rm9yU2ltcGxlQm9hcmQwMlByb2plY3RNYWRlQnlaaHl1bktpbU9yV2xndXNLaW0=

