server:
  port: 0
  servlet:
    context-path: /api/user

spring:
  application:
    name: user-server
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    import:
      - classpath:password.yml
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/simple-board02
    username: ${mariadb.username}
    password: ${mariadb.password}

  sql:
    init:
      mode: always
      platform: mariadb

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 465
    username: gimwlgus@gmail.com
    password: ${email.password.gmail}
    default-encoding: UTF-8
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  security:
    debug: false

springdoc:
  show-login-endpoint: true


---

spring:
  config:
    import: classpath:password.yml
    activate:
      on-profile: local

  h2:
    console:
      path: /h2/user
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./simpleBoard02/b-server-user/h2/member;AUTO_SERVER=true;mode=MYSQL;
    username: sa

  sql:
    init:
      mode: always
      platform: h2

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 465
    username: gimwlgus@gmail.com
    password: ${email.password.gmail}
    default-encoding: UTF-8
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  security:
    debug: true

springdoc:
  show-login-endpoint: false

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace


---

spring:
  config:
    activate:
      on-profile: common

swagger:
  server: http://localhost:8080

sign-up:
  key:
    session: "SESSION_ID:" # SessionUserServiceImpl
    email: "EMAIL:"        # EmailAuthDto.getEmail()
    nickname: "NICKNAME:"  # NicknameDto.getNickname()
  email:
    expire: 60 # TimeUnit: Second
  session:
    expire: 30 # TimeUnit: Minute
  admin:
    gimwlgus@gmail.com,
    gimwlgus@daum.net

withdrawal:
#  cron: "0 0 3 * * *" # 매일 3시 삭제 실행
  cron: "0 0/1 * * * *" # 1분 0초마다 삭제 실행
  expiration-time: 30
  expiration-time-unit: s # d: Day , h: Hour, m: Minute, s: Second

token:
  expiration-time: 30
  expiration-time-unit: d # d: Day , h: Hour, m: Minute, s: Second
  secret: VGhpc2lzSnd0U2VjcmV0S2V5Rm9yU2ltcGxlQm9hcmQwMlByb2plY3RNYWRlQnlaaHl1bktpbU9yV2xndXNLaW0=

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

