services:
  redis:
    extends:
      file: ./simpleBoard02/compose-local.yml
      service: redis

  discovery-server:
    extends:
      file: ./discovery/compose.yml
      service: discovery-server

  gateway-server:
    extends:
      file: ./discovery/compose.yml
      service: gateway-server
    environment:
      spring.profiles.active: local

  user-server:
    extends:
      file: ./simpleBoard02/compose-local.yml
      service: user-server
    environment:
      spring.profiles.active: local
    depends_on:
      gateway-server:
        condition: service_healthy

  article-server:
    extends:
      file: ./simpleBoard02/compose-local.yml
      service: article-server
    environment:
      spring.profiles.active: local
    depends_on:
      gateway-server:
        condition: service_healthy


networks:
  simple-board-02-network:
    external: true
