services:
  discovery-server:
    build: ./discovery/server-eureka
    extends:
      file: ./discovery/compose.yml
      service: discovery-server

  gateway-server:
    build: ./discovery/server-gateway
    extends:
      file: ./discovery/compose.yml
      service: gateway-server
    environment:
      spring.profiles.active: local

  redis:
    extends:
      file: ./simpleBoard02/compose.yml
      service: redis
    volumes:
      - ./db-data/redis:/data

  mariadb:
    extends:
      file: ./simpleBoard02/compose.yml
      service: mariadb
    env_file: ./simpleBoard02/.mariadb_local_env
    volumes:
      - ./db-data/mariadb:/var/lib/mysql:Z

  user-server:
    build: ./simpleBoard02/b-server-user
    extends:
      file: ./simpleBoard02/compose.yml
      service: user-server
    environment:
      swagger.server: http://localhost:8080
      client.server: http://gateway-server:8080
      token.expiration-time: 1
      token.expiration-time-unit: m # d: Day , h: Hour, m: Minute, s: Second

  article-server:
    build: ./simpleBoard02/c-server-article
    extends:
      file: ./simpleBoard02/compose.yml
      service: article-server
    environment:
      swagger.server: http://localhost:8080


networks:
  simple-board-02-network:
    external: true
