services:
  discovery-server:
    build: ./discovery/server-eureka
    extends:
      file: ./discovery/compose.yml
      service: discovery-server

  gateway-server:
    build: ./discovery/server-gateway
    extends:
      file: ./discovery/compose.yml
      service: gateway-server
    environment:
      spring.profiles.active: local

  redis:
    extends:
      file: ./simpleBoard02/compose.yml
      service: redis
    volumes:
      - ./db-data/redis:/data

  mariadb:
    extends:
      file: ./simpleBoard02/compose.yml
      service: mariadb
    env_file: ./simpleBoard02/.mariadb_local_env
    volumes:
      - ./db-data/mariadb:/var/lib/mysql:Z

  user-server:
    build: ./simpleBoard02/b-server-user
    extends:
      file: ./simpleBoard02/compose.yml
      service: user-server

  article-server:
    build: ./simpleBoard02/c-server-article
    extends:
      file: ./simpleBoard02/compose.yml
      service: article-server


networks:
  simple-board-02-network:
    external: true
