services:
  redis:
    extends:
      file: ./simpleBoard02/compose.yml
      service: redis

  mariadb:
    extends:
      file: ./simpleBoard02/compose.yml
      service: mariadb

  discovery-server:
    extends:
      file: ./discovery/compose.yml
      service: discovery-server

  gateway-server:
    extends:
      file: ./discovery/compose.yml
      service: gateway-server


  user-server:
    extends:
      file: ./simpleBoard02/compose.yml
      service: user-server

  article-server:
    extends:
      file: ./simpleBoard02/compose.yml
      service: article-server


networks:
  simple-board-02-network:
    external: true
