### 전체 조회
GET http://localhost:8080/api/article/all

### 특정 유저 조회
GET http://localhost:8080/api/article/all/user/1

### 특정 유저 상세 조회
GET http://localhost:8080/api/article/2/user/1
Content-Type: application/json

### 게시글 등록
POST http://localhost:8080/api/article/save/user/1
Content-Type: application/json
X-TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaW13bGd1c0BrYWthby5jb20iLCJpZCI6MSwiZXhwIjoxNzE2NTg5MzA0fQ.T1QIxZPw3MUuxEIohGaBIlyVxLpDycQsgVC__Kdr5Jz-A8KQ32hnltx-OgSKnYBSIq_ZnCxZjhal_WISL0FJjQ

{
  "userId": 1,
  "title": "제목 ",
  "content": "내용 "
}


### 게시글 수정
PUT http://localhost:8080/api/article/2/user/1
Content-Type: application/json
X-TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaW13bGd1c0BrYWthby5jb20iLCJpZCI6MSwiZXhwIjoxNzE2NTg5MzA0fQ.T1QIxZPw3MUuxEIohGaBIlyVxLpDycQsgVC__Kdr5Jz-A8KQ32hnltx-OgSKnYBSIq_ZnCxZjhal_WISL0FJjQ

{
  "id": 1,
  "userId": 1,
  "articleId": 2,
  "title": "유저id 1 2번 글 수정",
  "content": "유저id 1 2번 내용 수정"
}


### 게시글 삭제
POST http://localhost:8080/api/article/delete/user/1
Content-Type: application/json
X-TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaW13bGd1c0BrYWthby5jb20iLCJpZCI6MSwiZXhwIjoxNzE2NTg5MzA0fQ.T1QIxZPw3MUuxEIohGaBIlyVxLpDycQsgVC__Kdr5Jz-A8KQ32hnltx-OgSKnYBSIq_ZnCxZjhal_WISL0FJjQ

{
  "userId": 1,
  "articleIds": [2,3]
}


### 탈퇴자 게시글 삭제
POST http://localhost:8080/api/article/delete/withdrawal
Content-Type: application/json

[1]
