services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    user: 1000:1000
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /usr/local/src/redis/simple-board02:/data
    networks:
      - simple-board-02-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 20s
      timeout: 5s
      retries: 3

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - TZ="Asia/Seoul"
    env_file: .mariadb_env
    volumes:
      - /usr/local/src/mariadb/data/simple-board02:/var/lib/mysql:Z
    networks:
      - simple-board-02-network
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh --connect --innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3

  user-server:
    container_name: user-server
    hostname: user-server
    environment:
      spring.profiles.active: prod
      eureka.client.service-url.defaultZone: http://discovery-server:8761/eureka
      spring.datasource.url: jdbc:mariadb://mariadb:3306/simple-board02
      spring.data.redis.host: redis
      spring.data.redis.port: 6379
    networks:
      simple-board-02-network:
        ipv4_address: 172.19.0.200
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy

  article-server:
    container_name: article-server
    hostname: article-server
    environment:
      spring.profiles.active: prod
      eureka.client.service-url.defaultZone: http://discovery-server:8761/eureka
      spring.datasource.url: jdbc:mariadb://mariadb:3306/simple-board02
      spring.data.redis.host: redis
      spring.data.redis.port: 6379
    networks:
      simple-board-02-network:
        ipv4_address: 172.19.0.201
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy


networks:
  simple-board-02-network:
    external: true
