### 로그인
POST http://localhost:8090/login
Content-Type: application/json

{
  "email": "gimwlgus@daum.net",
  "password": "1234"
}

### 유저 조회
GET http://localhost:8090/user
X-TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaW13bGd1c0BkYXVtLm5ldCIsImlkIjoxLCJleHAiOjE3MDQ3MzEwNDR9.EiAJOaAa37BcXe6bkd189cSuYaggUgURMlxNa8gjtgzBAN7-8vuJpMQvDZ1bVWudorhvEla18Cae7s3lThqadg

### 유저 조회
GET http://localhost:8090/user/1
X-TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaW13bGd1c0BkYXVtLm5ldCIsImlkIjoxLCJleHAiOjE3MDQ3MzEwNDR9.EiAJOaAa37BcXe6bkd189cSuYaggUgURMlxNa8gjtgzBAN7-8vuJpMQvDZ1bVWudorhvEla18Cae7s3lThqadg

### 유저 정보 수정
PUT http://localhost:8090/user/1
X-TOKEN: Bearer
Content-Type: application/json

{
  "id": 1,
  "email": "gimwlgus@daum.net",
  "nickname": "얼거스",
  "password": "1234"
}

### 로그아웃
POST http://localhost:8090/logout
X-TOKEN: Bearer


