### 로그인
POST http://localhost:8080/api/userEntity/login
Content-Type: application/json

{
  "email": "gimwlgus@kakao.com",
  "password": "1234"
}

### 유저 조회
GET http://localhost:8080/api/userEntity/userEntity/1
X-TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaW13bGd1c0BrYWthby5jb20iLCJpZCI6MSwiZXhwIjoxNzE2NTg1MjE4fQ.ktATFWxAjEtaRZXnrWzrmqxUOGNtSGJSekpxJsdae3XeLG3yWpu3ZTiAN600mfSaAP54nv9q2H2v5Y5qkV9qsQ


### 유저 정보 수정
PUT http://localhost:8080/api/userEntity/userEntity/1
X-TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaW13bGd1c0BrYWthby5jb20iLCJpZCI6MSwiZXhwIjoxNzE2NTg1MjE4fQ.ktATFWxAjEtaRZXnrWzrmqxUOGNtSGJSekpxJsdae3XeLG3yWpu3ZTiAN600mfSaAP54nv9q2H2v5Y5qkV9qsQ
Content-Type: application/json

{
  "id": 1,
  "email": "gimwlgus@kakao.com",
  "nickname": "얼구스",
  "password": "1234"
}

### 로그아웃
POST http://localhost:8080/api/userEntity/logout
X-TOKEN: Bearer

### 탈퇴
POST http://localhost:8080/api/userEntity/withdrawal
X-TOKEN: Bearer


