### 닉네임 중복 확인
GET http://localhost:8080/api/userEntity/check?nickname=얼구스

### 이메일 중복 확인
GET http://localhost:8080/api/userEntity/check?email=gimwlgus@kakao.com

### 이메일 전송
POST http://localhost:8080/api/userEntity/check/auth
Content-Type: application/json

{
  "email": "gimwlgus@kakao.com"
}

### 이메일 인증 코드 검증
GET http://localhost:8080/api/userEntity/check/auth?code=3577ef

### 회원가입
POST http://localhost:8080/api/userEntity/sign-up
Content-Type: application/json

{
  "email": "gimwlgus@kakao.com",
  "nickname": "얼구스",
  "password": "1234"
}
