### 닉네임 중복 확인
GET http://192.168.219.105:8080/api/user/check?nickname=얼구스

### 이메일 중복 확인
GET http://192.168.219.105:8080/api/user/check?email=gimwlgus@kakao.com

### 이메일 전송
POST http://192.168.219.105:8080/api/user/check/auth
Content-Type: application/json

{
  "email": "gimwlgus@kakao.com"
}

### 이메일 인증 코드 검증
GET http://192.168.219.105:8080/api/user/check/auth?code=318542

### 회원가입
POST http://192.168.219.105:8080/api/user/sign-up
Content-Type: application/json

{
  "email": "gimwlgus@kakao.com",
  "nickname": "얼구스",
  "password": "1234"
}
