### 닉네임 중복 확인
GET http://localhost:8080/api/user/check/duplicate-nickname?nickname=얼구스s

### 이메일 중복 확인
GET http://localhost:8080/api/user/check/duplicate-email?email=gimwlgus@daum.net

### 이메일 전송
POST http://localhost:8080/api/user/check/auth
Content-Type: application/json

{
  "email": "gimwlgus@daum.net"
}

### 이메일 인증 코드 검증
GET http://localhost:8080/api/user/check/auth?code=fc06d3

### 회원가입
POST http://localhost:8080/api/user/sign-up
Content-Type: application/json

{
  "email": "gimwlgus@daum.net",
  "nickname": "얼구스",
  "password": "1234"
}
