services:
  discovery-server:
    container_name: discovery-server
    hostname: discovery-server
    ports:
      - 8761:8761
    networks:
      simple-board-02-network:
        ipv4_address: 172.19.0.100
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8761 || exit 1" ]

  gateway-server:
    container_name: gateway-server
    hostname: gateway-server
    ports:
      - 8080:8080
    environment:
      spring.profiles.active: prod
      eureka.client.service-url.defaultZone: http://discovery-server:8761/eureka
    networks:
      simple-board-02-network:
        ipv4_address: 172.19.0.101
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/healthcheck || exit 1" ]


networks:
  simple-board-02-network:
    external: true
