### login
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "gimwlgus@kakao.com",
  "password": "1234"
}

### 탈퇴 유저 게시글 삭제
DELETE http://localhost:8080/withdrawal/articles
Content-Type: application/json

[1]

### 게시글 삭제
DELETE http://localhost:8080/2/articles
Content-Type: application/json
X-TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaW13bGd1c0BnbWFpbC5jb20iLCJpZCI6MiwiZXhwIjoxNzA3NDE3NTc2fQ.3p1pk4Il-lmtq8jlYS5xyKd_78ehPYt-WyVHkN6XrvYq6fGCfnLdRmZrPOvC52nZBcYfGLzz7wUxR8dXOzlQug

{
  "userId": 2,
  "articleIds": [1,3]
}

