### 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "gimwlgus@kakao.com",
  "password": "1234"
}

### 유저 조회
GET http://localhost:8080/user/6
X-TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaW13bGd1c0BrYWthby5jb20iLCJpZCI6NiwiZXhwIjoxNzA3NTcxODUyfQ.hJHr0EhHnhMsoREWFBRol1pGca0p41tI_R0QfNv7Q28gy4h-EGxLBcMN82Gcqa7JD497ZTnps0eqKixr7tZOeQ


### 유저 정보 수정
PUT http://localhost:8080/user/6
X-TOKEN: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJnaW13bGd1c0BrYWthby5jb20iLCJpZCI6NiwiZXhwIjoxNzA3NTcxODUyfQ.hJHr0EhHnhMsoREWFBRol1pGca0p41tI_R0QfNv7Q28gy4h-EGxLBcMN82Gcqa7JD497ZTnps0eqKixr7tZOeQ
Content-Type: application/json

{
  "id": 6,
  "email": "gimwlgus@kakao.com",
  "nickname": "얼구스",
  "password": "1234"
}

### 로그아웃
POST http://localhost:8080/logout
X-TOKEN: Bearer

### 탈퇴
DELETE http://localhost:8080/withdrawal
X-TOKEN: Bearer


