server:
  port: 8100

spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    url: jdbc:h2:./simpleBoard02/server-c-article/h2/article;AUTO_SERVER=true;mode=MYSQL;
    username: sa

  sql:
    init:
      mode: always
#      mode: never

  jpa:
    hibernate:
      ddl-auto: create
#      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.sql: debug

---

key:
  redis:
    articleId: "ARTICLE_ID:"
token:
  secret: VGhpc2lzSnd0U2VjcmV0S2V5Rm9yU2ltcGxlQm9hcmQwMlByb2plY3RNYWRlQnlaaHl1bktpbU9yV2xndXNLaW0=
