server:
  port: 0
  servlet:
    context-path: /api/article

spring:
  application:
    name: article-server
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common

---

spring:
  config:
    import:
      - classpath:password.yml
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/simple-board02
    username: ${mariadb.username}
    password: ${mariadb.password}

  sql:
    init:
      mode: always
      platform: mariadb

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

---

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      path: /h2/article
      enabled: true
      settings:
        web-allow-others: true

  datasource:
    url: jdbc:h2:./simpleBoard02/c-server-article/h2/article;AUTO_SERVER=true;mode=MYSQL;
    username: sa

  sql:
    init:
      mode: always
      platform: h2

  jpa:
    hibernate:
#      ddl-auto: create
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

logging:
  level:
    org.hibernate.sql: debug

---

spring:
  config:
    activate:
      on-profile: common

swagger:
  server: http://localhost:8080

key:
  redis:
    articleId: "ARTICLE_ID:"
token:
  secret: VGhpc2lzSnd0U2VjcmV0S2V5Rm9yU2ltcGxlQm9hcmQwMlByb2plY3RNYWRlQnlaaHl1bktpbU9yV2xndXNLaW0=

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

