name: simple board 02 ci/cd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get Github Repository files
        uses: actions/checkout@v4

      - name: install JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 19

      - name: Setup Gradle 8.5
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5

      - name: 비공개 정보 담긴 파일 추가
        run: |
          echo "${{ secrets.PASSWORD_YML }}" > simpleBoard02/b-server-user/src/main/resources/password.yml
          echo "${{ secrets.PASSWORD_YML }}" > simpleBoard02/c-server-article/src/main/resources/password.yml
          echo "${{ secrets.MARIADB_ENV }}" > simpleBoard02/.mariadb_env

      - name: gradle build - discovery
        run: |
          cd discovery
          gradle clean build

      - name: gradle build - simpleBoard02
        run: |
          cd simpleBoard02
          gradle clean build

      - name: docker registry login
        run: |
          echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login \
          -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} \
          --password-stdin \
          registry.zhyun.kim

      - name: docker image push
        run: |
          docker compose -f compose-build.yml build --push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: docker compose 파일 압축
      run: |
        tar -czvf compose.tar.gz \
          compose.yml \
          discovery/compose.yml \
          simpleBoard02/compose.yml

    - name: docker compose 파일 전송
      uses: appleboy/scp-action@v0.1.7
      with:
        port: ${{ secrets.ZHYUN_PORT }}
        host: ${{ secrets.ZHYUN_HOST }}
        username: ${{ secrets.ZHYUN_USERNAME }}
        key: ${{ secrets.ZHYUN_SSH_KEY }}
        passphrase: ${{ secrets.ZHYUN_SSH_KEY_PASSPHRASE }}
        source: compose.tar.gz
        target: /usr/local/src/docker/simple-board-02

  play:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: docker compose 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          port: ${{ secrets.ZHYUN_PORT }}
          host: ${{ secrets.ZHYUN_HOST }}
          username: ${{ secrets.ZHYUN_USERNAME }}
          key: ${{ secrets.ZHYUN_SSH_KEY }}
          passphrase: ${{ secrets.ZHYUN_SSH_KEY_PASSPHRASE }}
          script: |
            cd /usr/local/src/docker/simple-board-02
            tar -xzvf compose.tar.gz
            rm -rf compose.tar.gz
            
            docker compose down --rmi local
            docker compose up -d 

